version: '3'

services:
  # Redis with TLS
  redis:
    image: redis:alpine
    networks:
      - api-network
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./tls/redis/redis.crt:/etc/redis/certs/redis.crt
      - ./tls/redis/redis.key:/etc/redis/certs/redis.key
      - ./tls/redis/ca.crt:/etc/redis/certs/ca.crt
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # Backend Service with TLS
  http-service:
    build:
      context: .
      dockerfile: http-service/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - api-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Tyk Gateway with TLS
  # tyk-gateway:
  #   build:
  #     context: .
  #     dockerfile: tyk/Dockerfile
  #   platform: linux/amd64
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - api-network
  #   volumes:
  #     - ./tyk.conf:/opt/tyk-gateway/tyk.conf
  #     - ./tls/tyk:/etc/tyk-gateway/certs
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     http-service:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=REDIS_PASSWORD
    
  # KrakenD Gateway
  # krakend:
  #   build:
  #     context: ./krakend
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - api-network
  #   depends_on:
  #     http-service:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  # Benchmark service
  # benchmark:
  #   build:
  #     context: .
  #     dockerfile: benchmark/Dockerfile
  #   networks:
  #     - api-network
  #   depends_on:
  #     tyk-gateway:
  #       condition: service_started
  #     krakend:
  #       condition: service_started
  #   volumes:
  #     - ./results:/results

networks:
  api-network:
    driver: bridge

volumes:
  redis_data: